### PR TITLE
Removed unnecessary encoding of paths

### PR DESCRIPTION
**Pull request by rui-castro**
Fixes issue keeps/roda/issues/943

### CODE REVIEW

**Comment by hsilva-keep** [comment]
@rui-castro @luis100 well, before this PR we had full URL-encode, and now we'll have no encode at all. The encoding was introduced (sadly we don't have full information about the reason) because some problem happened. And, by removing the encoding, we will have problems again. Is this the way to go?

**Comment by luis100** [comment]
I am sure we need to at least test the system with characters in the URL that are illegal for the URL and for the XML.

https://perishablepress.com/stop-using-unsafe-characters-in-urls/

The table on the link above shows that the following would need to be encoded:
- ASCII Control characters: Includes the ISO-8859-1 (ISO-Latin) character ranges 00-1F hex (0-31 decimal) and 7F (127 decimal.)
- Non-ASCII characters: Includes the entire “top half” of the ISO-Latin set 80-FF hex (128-255 decimal.)
- Reserved characters: `; / ? : @ = &` (does not include blank space)
- Unsafe characters: Includes the blank/empty space and ``" < > # % { } | \ ^ ~ [ ] ` ``

@rui-castro I suggest you test the generation of METS using files with the characters above on the name and check if it is still a valid XML and URL (using xmllint and the METS and xlink schemas).

**Comment by rui-castro** [comment]
@luis100 the mets writer always writes valid XML, right?

**Comment by luis100** [comment]
@rui-castro are you sure about that? I am not...

**Comment by rui-castro** [comment]
@luis100 this PR fixes the issue keeps/roda/issues/943. If you find a bug in my code, please let me know and I'll fix it.

**Comment by luis100** [comment]
I've improved current tests to include testing the encoding at my branch (lf_dev) after merging with your pull request:

https://github.com/keeps/commons-ip/blob/lf_dev/src/test/java/org/roda_project/commons_ip/model/impl/eark/EARKTest.java#L121

The tests **fail** because the produced METS it is **NOT valid**.

```
org.xml.sax.SAXParseException; systemId: file:/tmp/temp5635430356598914484/representations/representation%201/METS.xml; lineNumber: 13; columnNumber: 85; An invalid XML character (Unicode: 0x1) was found in the value of attribute "xlink:href" and element is "FLocat".
```

**Comment by luis100** [comment]
Note that the exception above was inside the failure validation report that makes the unit test fail.

**Comment by luis100** [comment]
@rui-castro please be aware that @hsilva-keep will create an issue on the commons-ip and will solve it. As I said before, if there is an issue on the supporting libraries (not your part) please report it.

**Comment by hsilva-keep** [comment]
Closing this PR without merging for the reasons already mentioned by @luis100

**Pull request closed without merging**
